name: "cli_dashboard"
version: "1.0.0"
config-version: 2

profile: "ci360_redshift"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  cli_dashboard:
    post-hook: "GRANT SELECT ON {{ this }} TO GROUP applications"
    marts:
      materialized: table
    staging:
      materialized: view
